name: anuga_env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - gdal
  - pytest
  - meshpy
  - cython
  - scipy
  - netcdf4
  - matplotlib
  - dill
  - future
  - gitpython
  - utm
  - pyproj
  - affine
  - openpyxl
  - pybind11
  - pymetis
  - mpi4py
  - Pmw
  - meson
  - meson-python
  - ninja
  - pkg-config
  - xarray
  - cartopy

