[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "anuga"
authors = [{name = "Stephen Roberts", email = "stephen.roberts@anu.edu.au"}]
dynamic = ["version", "description"]
dependencies = ["python >= 3.5",
                "nose",
                "numpy",
                "scipy",
                "netcdf4",
                "matplotlib",
                "gdal",
                "dill",
                "cython",
                "future",
                "mpi4py",
                "Pmw",
                "triangle"]
