[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "anuga"
authors = [{name = "stoiver", email = "stoiver@gmail.com"}]
dynamic = ["version", "description"]
