# Need to setup numpy.pc (in tools directory) to ensure 
# meson build finds the numpy headers. Also need to change 
# pyproject.toml to use the correct python 3.8

name: anuga_env_3.8
channels:
  - conda-forge
dependencies:
  - python=3.8.18
  - pip=24.3.1
  - affine=2.4.0
  - cartopy=0.21.1
  - cython=3.0.11
  - dill=0.3.9
  - future=1.0.0
  - gdal=3.7.0
  - gitpython=3.1.43
  - matplotlib=3.7.3
  - meshpy=2022.1.3
  - meson=1.6.0
  - meson-python=0.17.1
  - mpi4py=4.0.0
  - netcdf4=1.6.4
  - ninja=1.12.1
  - numpy=1.24.3
  - backports.zoneinfo=0.2.1
  - openpyxl=3.1.5
  - pandas=1.5.3
  - pkg-config=0.29.2
  - pybind11=2.13.6
  - pymetis=2023.1.1
  - pyproj=3.5.0
  - pytest=8.3.4
  - scipy=1.10.1
  - utm=0.7.0
  - wheel=0.45.1
  - xarray=2023.1.0
  - pip:
    - pmw
