name: anuga_env_3.11
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - affine
  - cartopy
  - cython
  - dill
  - future
  - gdal
  - gitpython
  - matplotlib
  - meshpy
  - meson
  - meson-python
  - mpi4py
  - netcdf4
  - ninja
  - numpy
  - openpyxl
  - pandas
  - pkg-config
  - pmw
  - pybind11
  - pymetis
  - pyproj
  - pytest=4.6.11
  - scipy
  - utm
  - wheel
  - xarray
