import os
Import('env')
instdir = os.path.join(env['PREFIX'], 'anuga', 'utilities')
env.Install(instdir, env.SharedLibrary('polygon_ext', ['polygon_ext.c']))
env.Install(instdir, env.SharedLibrary('util_ext', ['util_ext.c']))
env.Install(instdir, env.SharedLibrary('sparse_ext', ['sparse_ext.c']))
