name: Conda setup

on: [push]

jobs:
  test_conda:
    name: Example (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -el {0}
        run: |
          conda info
          pwd
          conda list
          pip install .
      - name: Conda list
        shell: bash -el {0}
        run: |
          conda install -c conda-forge -f environments/environment_${{matrix.python-version}}.yml
          python --version
          pytest -q --pyargs anuga