name: Conda setup

on: [push]

jobs:
  test_conda:
    name: Example (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install Our own environment
        shell: bash -el {0}
        run: |
          conda env create --name anuga_env --file environments/environment_${{matrix.python-version}}.yml
      - name: Install package
        shell: bash -el {0}
        run: |
          conda activate anuga_env
          pip install -v .
      - name: Test package
        shell: bash -el {0}
        run: |
          conda activate anuga_env
          cd ..
          pytest -q --pyargs anuga