name: Python Package using Conda

on: [push]

jobs:
  build-linux:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"] 
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda update --yes conda
        conda env create -n anuga_env -f environments/environment_{{matrix.python-version}}.yml
        # conda create -n anuga_env --yes -c conda-forge python=3.12 compilers numpy scipy \
        #     cython netcdf4 nose matplotlib gdal dill gitpython mpi4py utm Pmw pymetis \
        #     meshpy pytest pyproj affine meson-python meson ninja xarray future pkg-config
    - name: Build with pip (using meson)
      run: |
        source $CONDA/bin/activate anuga_env
        python --version
        python -m pip install .
    # - name: Lint with flake8
    #   run: |
    #     conda install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        source $CONDA/bin/activate anuga_env
        # check where we are
        pwd
        cd ..
        pytest -q --pyargs anuga
